# Generated by Django 4.2.30 on 2026-04-14 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=120, unique=True)),
                ('badge_description', models.TextField()),
                ('points_threshold', models.PositiveIntegerField(blank=True, null=True)),
                ('week_number_nullable', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('theme', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=False)),
                ('unlock_rule', models.CharField(blank=True, max_length=255)),
                ('scenario_title', models.CharField(blank=True, max_length=255)),
                ('scenario_narrative', models.TextField(blank=True)),
                ('clue_panel', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='WeekStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('step_name', models.CharField(max_length=160)),
                ('instructions', models.TextField()),
                ('max_points', models.PositiveIntegerField()),
                ('ai_enabled', models.BooleanField(default=False)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('guidance_prompts', models.JSONField(blank=True, default=list)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='campaign.week')),
            ],
            options={
                'ordering': ['week__week_number', 'step_number'],
                'unique_together': {('week', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('draft', 'Draft'), ('ai-assisted', 'AI Assisted'), ('final', 'Final')], max_length=24)),
                ('raw_user_input', models.TextField(blank=True)),
                ('opportunity_notes', models.TextField(blank=True)),
                ('ai_generated_output', models.TextField(blank=True)),
                ('ai_explanation', models.TextField(blank=True)),
                ('final_user_submission', models.TextField(blank=True)),
                ('user_review_confirmed', models.BooleanField(default=False)),
                ('was_user_edited', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='campaign.weekstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='campaign.week')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StepCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_text', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('required_for_full_score', models.BooleanField(default=True)),
                ('week_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='campaign.weekstep')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_points', models.PositiveIntegerField()),
                ('max_points', models.PositiveIntegerField()),
                ('evaluator_feedback', models.TextField(blank=True)),
                ('criteria_json', models.JSONField(blank=True, default=list)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='campaign.weekstep')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='campaign.submission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='campaign.week')),
            ],
            options={
                'ordering': ['-scored_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='campaign.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
